name: "sigstore"
version: "0.1.5"
usage: "Integrates Helm into Sigstore"
description: |-
  This plugin integrates Helm into the Sigstore ecosystem.
command: "$HELM_PLUGIN_DIR/bin/helm-sigstore"
hooks:
  install: "$HELM_PLUGIN_DIR/scripts/install-binary.sh"
  update: "$HELM_PLUGIN_DIR/scripts/install-binary.sh"
